; name:        led_blink.asm
; assemble:    avra led_blink.asm
; flash:       avrdude -p m328p -c stk500v1 -b 57600 -P /dev/ttyACM0 -U flash:w:led_blink.hex
; description: It turns the LED at PB5 (digital out 13) on and off with a delay of 5secs.
; source:      http://www.rjhcoding.com/avr-asm-led-blink.php

.nolist
.include "./m328Pdef.inc"
.list

.cseg
.org 0x00

start:

    ldi     r16,0xFF ; r16 = 0xFF (255)
    out     DDRB,r16 ; Out writes to SRAM, which is one way of accessing pins. DDRB controls PORTB's in/out state.
    ldi     r16,0x20 ; r16 is where we'll store current LED state, 0x00 means all pins low.
    out     PORTB,r16 ; set all B pins to current state. PORTB is where our favorite flashing pin is (pin 13)!
    
    call    delay
    
    ldi     r16,0xFF ; r16 = 0xFF (255)
    out     DDRB,r16 ; Out writes to SRAM, which is one way of accessing pins. DDRB controls PORTB's in/out state.
    ldi     r16,0x00 ; r16 is where we'll store current LED state, 0x20 means pin 13 high.
    out     PORTB,r16 ; set all B pins to current state. PORTB is where our favorite flashing pin is (pin 13)!

    call    delay

    ldi     r16,0xFF ; r16 = 0xFF (255)
    out     DDRB,r16 ; Out writes to SRAM, which is one way of accessing pins. DDRB controls PORTB's in/out state.
    ldi     r16,0x00 ; r16 is where we'll store current LED state, 0x00 means all pins low.
    out     PORTB,r16 ; set all B pins to current state. PORTB is where our favorite flashing pin is (pin 13)!
    
loop:    
    jmp     start

; Assembly code auto-generated by utility from Bret Mulvey
; Delay 79 999 991 cycles 4s 999ms 999us 437 1/2 ns at 16.0 MHz
; http://darcy.rsgc.on.ca/ACES/TEI4M/AVRdelay.html
delay:
    ldi  r18, 2
    ldi  r19, 150
    ldi  r20, 216
    ldi  r21, 6
L1: dec  r21
    brne L1
    dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    rjmp PC+1
    ret
