;name:            led_blink.asm
;assemble:        avra led_blink.asm
;flash:           avrdude -p m328p -c stk500v1 -b 57600 -P /dev/ttyACM0 -U flash:w:led_blink.hex
;description:     Toggles PB5 (led at pin 13) constantly on and of with a 4secs delay.
;inspir(at)ed by: http://www.rjhcoding.com/avr-asm-led-blink.php
;nov 5, 2021 - agguro - no-license license

.cseg
.org 0x00

start:
    ldi     r22,0b00100000  
    ldi     r16,0b00100000  ;r16 = 0x20 PB5 as output
    out     0x04,r16        ;r16 to DDRB (0x04) controls PORTB's in/out state.
    ;re-use r16 = 0x00100000 to set PB5 high (the famous pin 13 on Arduino Uno Rev3)
loop:
    out     0x05,r16        ;set PORTB with values from r16, pin 13 = low
    call    delay
    
    eor     r16,r22         ;toggle bit PB5
    jmp     loop
    
    

;Assembly code auto-generated by utility from Bret Mulvey
;Delay 79 999 991 cycles 4s 999ms 999us 437 1/2 ns at 16.0 MHz
;http://darcy.rsgc.on.ca/ACES/TEI4M/AVRdelay.html
delay:
    ldi  r18, 2
    ldi  r19, 150
    ldi  r20, 216
    ldi  r21, 6
l1:
    dec  r21
    brne l1
    dec  r20
    brne l1
    dec  r19
    brne l1
    dec  r18
    brne l1
    rjmp PC+1
    ret
