; name:        led_onoff.asm
; assemble:    avra led_onoff.asm
; flash:       avrdude -p m328p -c stk500v1 -b 57600 -P /dev/ttyACM0 -U flash:w:led_onoff.hex
; description: It turns the LED at PB5 (digital out 13) on and after a delay of 2 seconds off again.
; source:      http://www.rjhcoding.com/avr-asm-led-blink.php

.nolist
.include "./m328Pdef.inc"
.list

.cseg
.org	0x00

start:

    ;turn led at pin 13 on
    ldi     r16,0xFF ; r16 = 0xFF (255)
    out     DDRB,r16 ; Out writes to SRAM, which is one way of accessing pins. DDRB controls PORTB's in/out state.
    ldi     r16,0x20 ; r16 is where we'll store current LED state, 0x00 means all pins low.
    out     PORTB,r16 ; set all B pins to current state. PORTB is where our favorite flashing pin is (pin 13)!
    
    ;wait 2 secs
    call    delay
    
    ;turn led off
    ldi     r16,0xFF ; r16 = 0xFF (255)
    out     DDRB,r16 ; Out writes to SRAM, which is one way of accessing pins. DDRB controls PORTB's in/out state.
    ldi     r16,0x00 ; r16 is where we'll store current LED state, 0x00 means all pins low.
    out     PORTB,r16 ; set all B pins to current state. PORTB is where our favorite flashing pin is (pin 13)!
    
loop:    
    jmp     loop

; Assembly code auto-generated by utility from Bret Mulvey
; Delay 31 999 991 cycles 1s 999ms 999us 437 1/2 ns at 16.0 MHz
; http://darcy.rsgc.on.ca/ACES/TEI4M/AVRdelay.html
delay:
    ldi     r18, 82
    ldi     r19, 43
    ldi     r20, 254
l1: 
    dec     r20
    brne    l1
    dec     r19
    brne    l1
    dec     r18
    brne    l1
    nop
    ret
